name: cryptoloop_tr
description: Binance TR spot strategy and paper trading
publish_to: "none"
version: 1.2.0+13
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.2
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  stream_channel: ^2.1.4
flutter:
  uses-material-design: true
